---
version: '3.8'
services:
  detector:
    build:
      context: ./
    volumes:
    - ./config.yaml:/etc/bluetooth_tracker/config.yaml
    - ./bt.py:/usr/src/detector/bt.py
    - ./bluetooth_device.py:/usr/src/detector/bluetooth_device.py
